name: Lab 3 Create Artificat
on:
  push:
    branches:
    - main
  pull requests:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v3
    - name: Use node.js 18 .x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
    - name: Pretend to build
      run: echo Pretending to build some kind of app...
    - name: Push artifact foo.txt
      uses: actions/upload-artificat@v3
      with:
        name: my-artifact
        path: foo.txt
 